### ISSUE TITLE
Woovi + DoeBem

### ISSUE THREAD

**Issue by vboechat** [sigcoding/doebem#19]
**Doe Bem:**

- [x] Outdated (and expensive) payment gateways (Issue #3)
- [x] Heavy website (Issue #1)
- [ ] Possibility to suspend donation in the website (Issue #10)
- [x] Improve transparency mechanism and accountability with donors (Issue #8)
- [ ] Insert a plugin to integrate donation and CRM (Issue #4)
- [x] Homepage responsibility (Issue #22)
- [x] Add a contact option that is not at the end of the questions page (Issue #9)
- [x] Fix share buttons, for example, "Share donation" button URL or "doebem" doesn't works, and only shows after donation by credit card. (Issue #6)
- [ ] Fix and insert thankful messages after donation (Issue #5)
- [x] Fix different formatting in different pages, for example, "Time" and "Methodology" (Issue #7) 
- [x] Update formations (Issue #13)
- [ ] Add translation with i18n (Issue #35)
